swagger: "2.0"
info:
  description: "jobad reader api"
  version: "1.0.0"
  title: "Jobad Reader Api"
  termsOfService: "tbc"
  contact:
    email: "apiteam@swagger.io"
host: "petstore.swagger.io"
basePath: "/api/v1/"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"

paths:
  /jobad/{id}:
    get:
      tags:
      - "JobAd Item"
      summary: "find jobad by id"
      description: ""
      operationId: "findJobAdById"
      produces:
        - "application/json"
      parameters:
      - in: "path"
        name: "id"
        description: "id of jobad"
        required: true
        type: "string"
      responses:
        200:
          description: get states ok
          schema:
            $ref: '#/definitions/JobAdItem'

definitions:
  BaseResponse:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"
  JobAdItem:
    type: "object"
    $ref: "#/definitions/BaseResponse"
    properties:
      id:
        type: "string"
      companyName:
        type: "string"
      title:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"