mongodb:
  host: 34.73.206.62
  port: 37017
  db: test
  auth:
    username: myUserAdmin
    password: abc123
    db: admin
  bulk:
    insert: 500
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    instance:
      appname: service-jobad-reader
server:
  port: 8763
spring:
  application:
    name: service-jobad-reader
com:
  dotterbear:
    feign:
      rss.reader:
        value: service-rss-reader
        path: /
