mongodb:
  host: 127.0.0.1
  port: 27017
  db: test
  auth:
    username: myUserAdmin
    password: abc123
    db: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-jobad-reader